version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - cd ..
      - yum install -y nuget
      - npm install bignumber.js
      - pip install lit OutputCheck pyyaml
      - find . -type f
      # Get Boogie
      # Some recent changes have broken one of our test cases, so lock down to a specific
      # release for now. See https://github.com/dafny-lang/dafny/issues/476.
      - git clone --branch v2.4.2 https://github.com/boogie-org/boogie.git
      - nuget restore boogie/Source/Boogie.sln
      - msbuild boogie/Source/Boogie.sln
      # Get Z3
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
      - unzip z3*.zip && rm *.zip
      - cp -r z3* dafny/Binaries/z3
      # NuGet
      - cd dafny
      - nuget restore Source/Dafny.sln
  build:
    commands:
      - msbuild Source/Dafny.sln
      - cd Test
      # The /optimize flag does not work on mono
      - find . -name "*.dfy" -exec sed -i 's!/optimize !!g' {} +
      - lit --time-tests -v .
